### ISSUE TITLE
Unable to decode WHEA Boot Error Record

### ISSUE THREAD

**Issue by kowjacalski** [ralish/DecodeWheaRecord#5]
Hello,

> d:\UTILS\DecodeWheaRecord>DecodeWheaRecord.exe 435045520101FFFFFFFF010003000000010000003C0100002B2A08001E0518159C6B0037C03500000000000000000000000000000000000000000000000000009C6B0037C0350000000000000000000066A4613D40AB9A40A698F362D464B38F0000000000000000000000000000000000000000000000000000000000000000C80000007400000000010000010000002F1CA4939FA0C2E7AC1FF2488F03EEC30000000000000000000000000000000003000000000000000000000000000000000000000000000007010100000000002F1CA4939FA0C2E7AC1FF2488F03EEC374000000560065006E00480077002800390033004100340031004300320046002D0041003000390046002D0045003700430032002D0041004300310046002D0046003200340038003800460030003300450045004300330029000000
> 
> [WHEA_ERROR_RECORD_HEADER] Expected major revision 2 but MajorRevision member is: 1

Microsoft-Windows-Kernel-WHEA/Errors from Windows 10 are not supported?

Could you please help decode this WHEA error?

**Comment by ralish** [comment]
@kowjacalski What version of Windows is this from?

**Comment by ralish** [comment]
@kowjacalski Nevermind, can decode part of the record. Will provide an update tomorrow.

**Comment by ralish** [comment]
So there's two issues here. The first is that the utility is exiting on decoding the error record if the revision doesn't match the latest version (v2.16). That's clearly wrong, and I've pushed an update which now only warns if a newer revision than what's expected is encountered, but continues to attempt to decode the record. That results in the following given your error record:

```
[WHEA_ERROR_RECORD_HEADER] Expected size: 128 | Current offset: 0
[WHEA_ERROR_RECORD_SECTION_DESCRIPTOR] Expected size: 72 | Current offset: 128
[WHEA_ERROR_RECORD] Header indicates error record contains 316 bytes but marshalled 200 bytes.
{
  "Header": {
    "Signature": "CPER",
    "Revision": {
      "MinorRevision": 1,
      "MajorRevision": 1
    },
    "SignatureEnd": 4294967295,
    "SectionCount": 1,
    "Severity": "Informational",
    "ValidBits": "PlatformId",
    "Length": 316,
    "PlatformId": "37006b9c-35c0-0000-0000-000000000000",
    "CreatorId": "37006b9c-35c0-0000-0000-000000000000",
    "NotifyType": "Boot Error Record (BOOT)",
    "RecordId": 0,
    "Flags": "",
    "Reserved": "AAAAAAAAAAA="
  },
  "SectionDescriptor": [
    {
      "SectionOffset": 200,
      "SectionLength": 116,
      "Revision": {
        "MinorRevision": 0,
        "MajorRevision": 1
      },
      "ValidBits": "",
      "Reserved": 0,
      "Flags": "Primary",
      "SectionType": "93a41c2f-a09f-e7c2-ac1f-f2488f03eec3",
      "SectionSeverity": "Informational"
    }
  ],
  "Section": []
}
```

So we can see a **Boot Error Record (BOOT)** has been logged at **Informational** severity. Unfortunately, the error record section isn't decoded (the remaining 116 bytes) as we don't know the structure for this type of section (given by the GUID: `93a41c2f-a09f-e7c2-ac1f-f2488f03eec3`). WHEA records are binary and each section has its own unique format, and many of these aren't documented. I couldn't find any information on this specific GUID, so it's probably defined by the manufacturer and non-public (e.g. by Intel).

A hex-dump of those 116 bytes gives:
```

**Comment by ralish** [comment]
@kowjacalski I analyzed the record you provided as best I can in the previous comment but accidentally posted a partial analysis, so any email you got is likely incomplete. See the full comment on GitHub for all the details.

**Comment by kowjacalski** [comment]
@ralish THANKS :)
It's something with Secure boot enabled/disabled. If I disable Secure Boot then this WHEA error/info shows up sometimes in Microsoft-Windows-Kernel-WHEA/Errors in Windows 10.

In Windows 11, this WHEA error/info no longer shows up in Microsoft-Windows-Kernel-WHEA/Errors even with Secure Boot disabled.

**Comment by ralish** [comment]
Mainly a note for future me if this type of error starts becoming more prominent, but the binary data in the error section is a UEFI Firmware Health Data Record. More details can be found in the ACPI Specification (Section 5.2.31.4 in v6.5a of the specification).
